#!/usr/bin/bash

# устанавливаем mysql сервер 5, pip3 для питона 7, ssh  для доступа с коносли 11, samba сделать сетевую папку 9,
# ставим библиотеки для обработки BUFR 14 и библиотеку для работы с базой mysql 20  

apt-get install -y mysql-server python3-pip samba ssh python-dev default-libmysqlclient-dev build-essential libssl-dev libffi-dev python-dev

pip3 install pybufrkit

pip3 install mysqlclient

#  запускаем скрипт создания баз для хранения расшифрованых телеграмм

mysql < tsaoscript.sql

# записываем в базу информацию о станциях и УГМС
cd .. 
python3 ./in_table_MYSQL_UGMS_and_Stations.py

# делаем папку folder_with_telegram сетевой, даем на нее права
cd ./folder_with_telegram
pwd=$(pwd)
sudo chmod -R 7777 $pwd
sudo chown -R nobody:nogroup $pwd

echo "[folder_with_telegram]
path = $pwd
browsable = yes
writable = yes
qest ok = yes
public = yes
read only = no" >> /etc/samba/smb.conf

echo FINISH
