-- MySQL Script generated by MySQL Workbench
-- Сб 07 сен 2019 21:38:40
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tsao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tsao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tsao` DEFAULT CHARACTER SET utf8 ;
USE `tsao` ;

-- -----------------------------------------------------
-- Table `tsao`.`UGMS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tsao`.`UGMS` (
  `idUGMS` INT NOT NULL AUTO_INCREMENT,
  `UGMS` VARCHAR(45) NULL,
  PRIMARY KEY (`idUGMS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tsao`.`Stations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tsao`.`Stations` (
  `numberStation` INT NOT NULL,
  `name_stations` VARCHAR(45) NULL,
  `UGMS_idUGMS` INT NOT NULL,
  PRIMARY KEY (`numberStation`),
  INDEX `fk_Stations_UGMS_idx` (`UGMS_idUGMS` ASC),
  CONSTRAINT `fk_Stations_UGMS`
    FOREIGN KEY (`UGMS_idUGMS`)
    REFERENCES `tsao`.`UGMS` (`idUGMS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tsao`.`releaseZonde`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tsao`.`releaseZonde` (
  `idRelease` INT NOT NULL,
  `Stations_numberStation` INT NOT NULL,
  `date` DATETIME NULL,
  `time` DATETIME NULL,
  `coordinateStation` VARCHAR(45) NULL,
  `device` VARCHAR(45) NULL,
  `height` VARCHAR(45) NULL,
  `numberOfWindShearLevels` VARCHAR(45) NULL,
  `numberOfObservations` VARCHAR(45) NULL,
  `numberSensing` VARCHAR(45) NULL,
  `identificationOfObservers` VARCHAR(45) NULL,
  `ground-baseRadiosondeSignalReceptionSystem` VARCHAR(45) NULL,
  `antennaHeightAboveSupportLevel` VARCHAR(45) NULL,
  `amendmentToTheOrientationOfTheAzimuth` VARCHAR(45) NULL,
  `correctionToTheOrientationOfTheCoenerOfTheSeat` VARCHAR(45) NULL,
  `radarDome` VARCHAR(45) NULL,
  `methodForDeterminingGeopotentialHeight` VARCHAR(45) NULL,
  `versionPO` VARCHAR(45) NULL,
  `radiosondeSerialNumber` VARCHAR(45) NULL,
  `correctionAlgorithimForHumidityMeasurement` VARCHAR(45) NULL,
  `carrierFrequency` VARCHAR(45) NULL,
  `pressureSensorType` VARCHAR(45) NULL,
  `temperatureSensorType` VARCHAR(45) NULL,
  `humiditySensorType` VARCHAR(45) NULL,
  `theConfigurationOfTheRadiosonde` VARCHAR(45) NULL,
  `configurationOfRadiosondeSuspension` VARCHAR(45) NULL,
  `theManufacturerOfTheShell` VARCHAR(45) NULL,
  `typeShell` VARCHAR(45) NULL,
  `theWeightOfTheShell` VARCHAR(45) NULL,
  `gasForFillingTheShell` VARCHAR(45) NULL,
  `counGas` VARCHAR(45) NULL,
  `longSuspension` VARCHAR(45) NULL,
  `reasonForDiscontinuation` VARCHAR(45) NULL,
  PRIMARY KEY (`idRelease`),
  INDEX `fk_releaseZonde_Stations1_idx` (`Stations_numberStation` ASC),
  CONSTRAINT `fk_releaseZonde_Stations1`
    FOREIGN KEY (`Stations_numberStation`)
    REFERENCES `tsao`.`Stations` (`numberStation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tsao`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tsao`.`table1` (
  `content_telegramm` INT NOT NULL,
  `Stations_numberStation` INT NOT NULL,
  `date` DATETIME NULL,
  `time` FLOAT NULL,
  `P` FLOAT NULL,
  `T` FLOAT NULL,
  `Td` FLOAT NULL,
  `H` FLOAT NULL,
  `D` FLOAT NULL,
  `V` FLOAT NULL,
  `dLat` FLOAT NULL,
  `dLon` FLOAT NULL,
  `Flags` VARCHAR(45) NULL,
  PRIMARY KEY (`content_telegramm`),
  INDEX `fk_table1_Stations1_idx` (`Stations_numberStation` ASC),
  CONSTRAINT `fk_table1_Stations1`
    FOREIGN KEY (`Stations_numberStation`)
    REFERENCES `tsao`.`Stations` (`numberStation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
